apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
          - name: mongodb.databasename
            value: userservice-dpy
          - name: mongodb.host
            value: mongo-service
          - name: mongodb.port
            value: "27017"
          - name: general.pageSize
            value: "20"
          - name: general.dateFormat
            value: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
          - name: eureka.client.service-url.defaultZone
            value: http://eureka-service:8761/eureka/
          - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
#      imagePullSecrets:
#      - name: registrypullsecret
